name: Test changed files in pull request to Main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CI: true
  NODE_VERSION: 18.16.0

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Running linter
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - run: |
          npm ci
          npm run lint

  tests:
    runs-on: ubuntu-latest
    needs: linter

    steps:
      - uses: actions/checkout@v3
      - name: Running tests
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - run: |
          cp .env.example .env
          npm ci
          npm run test:ci
